# Generated by Django 5.0.3 on 2024-04-02 04:52

from django.db import migrations

def insertar_datos(apps, SchemaEditor):
    ExceptionType = apps.get_model('exceptions', 'ExceptionType')

    ExceptionType.objects.create(description='Secuencial')
    ExceptionType.objects.create(description='De Campos')
    ExceptionType.objects.create(description='De Tabla')
    ExceptionType.objects.create(description='Personalizado')

class Migration(migrations.Migration):

    dependencies = [
        ('exceptions', '0001_exception_type')
    ]

    operations = [
        migrations.RunPython(insertar_datos)
    ]
