# Generated by Django 5.0.3 on 2024-04-03 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria_bd_api', '0005_result_exception_ocurred'),
        ('exceptions', '0003_customqueries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customqueries',
            name='connection',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='auditoria_bd_api.databaseconnection'),
        ),
    ]
