# Generated by Django 5.0.3 on 2024-04-03 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria_bd_api', '0005_result_exception_ocurred'),
        ('exceptions', '0004_alter_customqueries_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='customqueries',
            name='only_this_connection',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customqueries',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria_bd_api.databaseconnection'),
        ),
        migrations.AlterField(
            model_name='customqueries',
            name='table',
            field=models.CharField(max_length=120),
        ),
    ]
