# Generated by Django 5.0.3 on 2024-03-21 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditoria_bd_api', '0002_databaseconnection_last_used'),
    ]

    operations = [
        migrations.AddField(
            model_name='databaseconnection',
            name='current_used',
            field=models.BooleanField(default=False),
        ),
    ]
