# Generated by Django 5.0.3 on 2024-04-02 04:52

from django.db import migrations

def insertar_datos(apps, SchemaEditor):
    UserModel = apps.get_model('auth', 'user')
    TokenModel = apps.get_model('authtoken', 'token')

    password = "123456"
    user = UserModel.objects.create_user(username="user", password=password, email="admin@admin.com")
    TokenModel.objects.create(user=user)




class Migration(migrations.Migration):

    dependencies = [
        ('auditoria_bd_api', '0006_alter_result_results')
    ]

    operations = [
        migrations.RunPython(insertar_datos)
    ]
